### ISSUE TITLE
Additional patches

### ISSUE THREAD

**Issue by ghost** [Prof9/NocashLauncher#1]
**Jhno591 commented on 7f0eca5 3 hours ago • edited**

> Hi there!
> 
> Would any of this stuff you could use are add to you're NocashLauncher ?
> 
> Although this is for no$gba v2.8d , not debugger, the addresses would have to be changed for debugger .
> 
> The EX5 would be useful extracted from no$zoomer memory.dll file
> 
> Download from here https://gbatemp.net/threads/no-gba-v2-8d-released-26-may-2016.428207/#post-6387844, package has the upx unpacker , can be use only on a fresh no$gba file to unpack it.
> 
> Issues also to be fixed is the bad sound I posted here - http://ngemu.com/threads/no-gba-v2-8c-released-07-may-2016.183657/#post-2480793
> 
> Can they be added as an "Option" ?, in NocashLauncher each setting ..
> 
> Hope its useful all best J591
> 
> ```
> (Note) Use with clean Emulator.
> 
> NO$GBA v2.8d upx:
> CMD command and ->
> CD C:\ - or path ?
> 
> first Unpack , second repack
> 
> upx -d NO$GBA.EXE
> upx NO$GBA.EXE
> ------------
> Hex Editor
> 
> Fix some Games, Rune factory a harvest moon est.
> 0x0005D8EF 80BDD40900 -> 80BDD40800
> 0x0005D901 01000000C3E9 -> 01010000C3E9
> 
> Frame skips
> 0x0005B2D7 0A730A -> 0B730A
> 0X0005D9CE 01E8A986FFFF2B05 -> 00E8A986FFFF2B05
> 
> Software Sound
> 0x0006B725 0102566F -> 0202566F
> 
> Bright Sunlight
> 0x0006B835 0002536F6C -> 0202536F6C
> 
> NDS-Lite in GBA mood (poppy)
> 0006B482 010347424120 -> 030347424120
> 
> NO$GBA v2.8c - EX5 Patch - Modded.
> 
> 0X0005D7FD 898518090000 - Normaly second one listed.
> 
> Emu address 0x0005D7FD
> Ram Address 0x0045DBFD -> E99E510D0009 Hooks to RAM 0X00532DA0
> 
> Add to Compressed Emulator at 0x000285A0 "Needed" ->
> 66 81 FA 00 B0 73 05 C1 E8 02 EB 00 C1 E3 02 89 85 18 09 00 00 E9 49 AE F2 FF
> 
> E949AEF2FF loop's back to 0x0045DC03 + 06
> 
> --------------
> 
> Add so no$gba can be unpacked and repacked using UPX
> 
> 66 89 3D 73 CD 46 00 66 89 15 75 CD 46 00 66 A3 77 CD 46 00
> C7 05 73 CD 46 00 F9 AA 46 35 66 C7 05 77 CD 46 00 62 6C 90
> ```

**Prof9 commented on 7f0eca5 2 hours ago • edited**

> A previous iteration of this program did indeed have an EX5 option, but I'm not really a fan of it as it makes CPU usage skyrocket (in my experience) and the games that matter already have antipiracy patches anyway. I thought EX5 wasn't needed for recent No$gba versions anymore but perhaps I'm wrong.
> 
> As for the other options, most of these don't look like they aid debugging in any way, perhaps you should be using the gaming version of No$gba instead of the debug version? Most of these settings can even be found in the options so there's really no need to hard patch them at all. Just to clarify, this tool is only intended for use with the debug version of No$gba.
> 
> By the way, in the future please open a GitHub issue for these sorts of things, commit comments are kind of hard to keep track of.

**Jhno591 commented on 7f0eca5 4 minutes ago • edited**

> I edited the main gaming version with these built into it.
> 
> Yes the ex5 is needed still for some games, check my video first few mins, video was a big speed up in game video footage , and some of the game play, I edited the original hex of ex5 so games run more smover then the original hex code, PS: I backup My own games!.
> 
> https://www.youtube.com/watch?v=Q_TE16Z3mSw
> 
> This one EX3 - Frame skips
> 0x0005B2D7 0A730A -> 0B730A
> 0X0005D9CE 01E8A986FFFF2B05 -> 00E8A986FFFF2B05
> ---
> 
> Fix some Games, Rune factory a harvest moon est.
> 0x0005D8EF 80BDD40900 -> 80BDD40800
> 0x0005D901 01000000C3E9 -> 01010000C3E9
> 
> Fixed games like rune factory with no frozen white screens at start, and pokemon B/W 2 Summery black screens frozen fix
> 
> Although just should be an enable/disable option just to bypass them bad parts in the games..
> 
> OK got you but the hex address can be changed for debugging version, HxD.exe for vurtal ram adress, Ollybug for hooking new ram adresses .
> 
> Although I could work on this if you like ?, make take little while.
> 
> Sorry NB here, will post there.

**Comment by ghost** [comment]
> antipiracy patches anyway. I thought EX5 wasn't needed for recent No$gba versions anymore but perhaps I'm wrong.

EX5 is not a patch for games, It's an arm9 arm7 timer Speed up / Slow down, it mess with them

http://ngemu.com/threads/no-zoomer-reversed.157822/

> EX5: Downclocking this seems to divide the ARM9 and/or ARM7 cpu clock by 16. This is reducing the cpu emulation load, and may make the emulation appear faster in some cases. Additionally it does seem to jump to bugged memory address. Results should be quite unpredictable. In some games EX5 seems to be actually fixing problems (probably timing glitches, which may get 'fixed' since EX5 is completely messing up timings).

---

PS: put you here might get some people nip in on your NocashLauncher

http://ngemu.com/threads/external-programs-for-no-gba.117392/page-7#post-2487249

**Comment by Prof9** [comment]
Then I am definitely not adding EX5. The goal here is not to actively break the emulation. I just made this to fix a small compatibility issue I was running into and to not give Nocash any extra work that he probably doesn't care about since I doubt he uses Windows 10 or Skype.

Either way the source is available and in the public domain, if you want to add any patches, you are free to redistribute it and make any sorts of modifications with or without credit.

Personally I will not be adding any of the following things in the foreseeable future.
- Patches for the gaming version of No$gba;
- Patches that are readily available in the options (of the debug version);
- Patches that alter how games are emulated, such as EX5;
- Patches for specific games;
- Patches that don't aid debugging in any way, such as noise filters, upscaling, frame skipping (in fact, the latter is even detrimental).

By the way, there is absolutely no point in porting the current NocashLauncher patches to the gaming version, it doesn't even have a debug font, it will not affect anything.

**Comment by ghost** [comment]
It's OK prof9, maybe someone might find it useful

Although I'm not good with making a patcher of any kind, I can add it into the emulator it's self though.

> By the way, there is absolutely no point in porting the current NocashLauncher patches to the gaming version, it doesn't even have a debug font, it will not affect anything.

The games do have same issues as Debugger, All I could do is Just locate the new Offsets for debugger version if any of them are useful are needed.., let us know, if not its ok.

All best in future of what you do! and nocash too.

> I doubt he uses Windows 10 or Skype.

Na, he's little low tex, He relies on Donations from his main site, where he gets game consoles and and stuff Donated, uses the main chip sets to make emulators/programs with.

**Comment by Prof9** [comment]
Alright, I'm closing this then.

> The games do have same issues as Debugger

I mean the issue that I specifically made NocashLauncher for. The font problem is exclusive to the debugger window which the No$gba gaming version doesn't have.
